# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c844d845377ca311dbdf49b92208215"
name = "Hatley Survey"
handle = "hatley-survey-1"
application_url = "https://belts-unavailable-caring-mainly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hatleydev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://belts-unavailable-caring-mainly.trycloudflare.com/auth/callback",
  "https://belts-unavailable-caring-mainly.trycloudflare.com/auth/shopify/callback",
  "https://belts-unavailable-caring-mainly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[app_proxy]
url = "https://belts-unavailable-caring-mainly.trycloudflare.com//app/questions"
subpath = "questions"
prefix = "apps"

[pos]
embedded = false
