# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "083c56ccec72e74aa89a8384a97bb4ad"
name = "Hatley Survey"
handle = "hatley-survey"
application_url = "https://scanned-nightmare-gazette-afghanistan.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testtakewithfood.myshopify.com"
include_config_on_deploy = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://scanned-nightmare-gazette-afghanistan.trycloudflare.com/auth/callback",
  "https://scanned-nightmare-gazette-afghanistan.trycloudflare.com/auth/shopify/callback",
  "https://scanned-nightmare-gazette-afghanistan.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
