# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c844d845377ca311dbdf49b92208215"
name = "Hatley Survey"
handle = "hatley-survey-1"
application_url = "https://packet-decreased-consult-syndrome.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hatleydev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://packet-decreased-consult-syndrome.trycloudflare.com/auth/callback",
  "https://packet-decreased-consult-syndrome.trycloudflare.com/auth/shopify/callback",
  "https://packet-decreased-consult-syndrome.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
