# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfc47f6268e562d54e62fde004e7c70e"
name = "Hatley Survey"
handle = "hatley-survey-3"
application_url = "https://mi-bubble-charms-virgin.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tanya-soni.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://mi-bubble-charms-virgin.trycloudflare.com/auth/callback",
  "https://mi-bubble-charms-virgin.trycloudflare.com/auth/shopify/callback",
  "https://mi-bubble-charms-virgin.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[app_proxy]
url = "https://mi-bubble-charms-virgin.trycloudflare.com/app/questions-three"
subpath = "questions"
prefix = "apps"

[pos]
embedded = false
